-- Seed Projects
INSERT INTO public.projects (id, title, slug, location, category, description, area, year, status, specifications, images) VALUES
('northwest-heights', 'Northwest Heights', 'northwest-heights', 'Tirupati, AP', 'Residential', 'A ultra-luxurious multi-family residential enclave combining cantilevered balconies, double-height floor-to-ceiling glass facades, and solar-smart roofing.', '14,500 sq.ft', '2025', 'Completed', ARRAY['Double-height living atrium', 'Private infinity deck', 'Smart home automation', 'VRF central air conditioning'], ARRAY['https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?q=80&w=1200&auto=format&fit=crop']),
('pineview-ridge', 'Pineview Ridge Residences', 'pineview-ridge-residences', 'Air By-Pass Road, Tirupati', 'Residential', 'A contemporary tropical villa featuring teak louvers, central open courtyard (Brahmasthan), water lily reflection pool, and Italian Statuario marble floors.', '9,800 sq.ft', '2025', 'Completed', ARRAY['Central courtyard pond', 'Custom teak woodwork', 'Italian Statuario flooring', '10kW rooftop solar grid'], ARRAY['https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=1200&auto=format&fit=crop']),
('carrefour-new-building', 'Carrefour New Building', 'carrefour-new-building', 'Balaji Colony, Tirupati', 'Commercial', 'A modern commercial hub featuring high-traffic retail spaces, basement automated car parking, and glass curtain wall elevation.', '28,000 sq.ft', '2024', 'Completed', ARRAY['Curtain wall structural glazing', 'Automated basement parking', 'High-speed capsule elevators', 'Seismic Zone III compliance'], ARRAY['https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop']),
('serene-haven-townhomes', 'Serene Haven Townhomes', 'serene-haven-townhomes', 'Renigunta Road, Tirupati', 'Architecture', 'A cluster of 12 luxury duplex townhomes boasting private terrace gardens, subterranean parking, and unified architectural elevation design.', '18,200 sq.ft', '2025', 'Completed', ARRAY['Private terrace gardens', 'Underground cabling network', 'Clubhouse & fitness suite', 'Rainwater harvesting shafts'], ARRAY['https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=1200&auto=format&fit=crop']),
('science-laboratory-hall', 'Science Laboratory Hall', 'science-laboratory-hall', 'University Zone, Tirupati', 'Commercial', 'A high-precision research facility equipped with vibration-isolated foundation slabs, HEPA cleanroom HVAC ducts, and acid-resistant chemical flooring.', '22,000 sq.ft', '2024', 'Completed', ARRAY['Vibration isolated foundation', 'Acid-resistant epoxy flooring', 'HEPA cleanroom ventilation', 'Emergency gas containment'], ARRAY['https://images.unsplash.com/photo-1562774053-701939374585?q=80&w=1200&auto=format&fit=crop']),
('northwest-building', 'The Northwest Building', 'the-northwest-building', 'Chittoor Highway, AP', 'Renovation', 'Complete structural retrofitting and modern glass facade transformation of a 20-year-old concrete building into a LEED-certified workspace.', '16,000 sq.ft', '2025', 'Completed', ARRAY['CFRP structural strengthening', 'HPL louver shading', 'Smart lighting controls', 'Zero operational downtime during retrofitting'], ARRAY['https://images.unsplash.com/photo-1541888946425-d0fbb186a5b3?q=80&w=1200&auto=format&fit=crop'])
ON CONFLICT (id) DO NOTHING;

-- Seed Materials
INSERT INTO public.materials (id, name, category, description, unit, price, image, available) VALUES
('steel-tmt', 'Primary TMT Rebars (Fe 550D)', 'Steel', 'High-ductility Fe 550D TMT steel rebars manufactured by Vizag Steel & Tata Tiscon, designed for superior seismic resistance and high tensile strength.', 'Ton', 68000, 'https://images.unsplash.com/photo-1535813547-99c456a41d4a?q=80&w=1200&auto=format&fit=crop', true),
('cement-opc', 'UltraTech & Coromandel OPC 53 Grade Cement', 'Cement', 'Premium Ordinary Portland Cement (OPC 53 Grade) offering fast setting time and ultra-high initial compressive strength.', 'Bag', 430, 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?q=80&w=1200&auto=format&fit=crop', true),
('wood-teak', 'CP Teakwood & Burma Teak Timber', 'Wood', 'Seasoned, termite-resistant first-quality Teakwood ideal for luxury entrance doors, window frames, and structural columns.', 'Cft', 3500, 'https://images.unsplash.com/photo-1546484475-7f7bd55792da?q=80&w=800&auto=format&fit=crop', true),
('plywood-bwp', 'BWP Grade Marine Plywood (IS 710)', 'Plywood', '100% Boiling Water Proof (BWP) Marine Plywood with anti-termite chemical treatment for kitchen cabinets and wet areas.', 'Sheet', 2400, 'https://images.unsplash.com/photo-1513694203232-719a280e022f?q=80&w=800&auto=format&fit=crop', true),
('glass-toughened', 'Saint-Gobain 12mm Toughened & DGU Glass', 'Glass', 'High-performance heat-strengthened architectural glass offering acoustic insulation, solar heat reduction, and safety.', 'Sq.Ft', 180, 'https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?q=80&w=800&auto=format&fit=crop', true),
('granite-black', 'Black Galaxy & Vizag Blue Granite', 'Granite', 'Premium polished natural granite slabs with high scratch resistance and deep luster for countertops and staircase steps.', 'Sq.Ft', 280, 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=800&auto=format&fit=crop', true),
('marble-italian', 'Italian Statuario & Botticino Marble', 'Marble', 'Export-grade imported Italian marble featuring elegant veining patterns, perfect for high-end villa flooring and feature walls.', 'Sq.Ft', 450, 'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=800&auto=format&fit=crop', true),
('tiles-vitrified', 'Large Format Vitrified Porcelain Tiles (8x4 ft)', 'Tiles', 'Seamless slab-sized glazed vitrified tiles with nano-polished surface and stain resistance.', 'Sq.Ft', 120, 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop', true),
('paint-royal', 'Asian Paints Royale Aspira Luxury Emulsion', 'Paint', 'Ultra-durable interior wall paint with Teflon surface protection, smooth sheen finish, and crack-bridging technology.', 'Litre', 480, 'https://images.unsplash.com/photo-1562259949-e8e7689d7828?q=80&w=800&auto=format&fit=crop', true),
('paint-exterior', 'Apex Ultima Protek Exterior Weatherproof Paint', 'Exterior Paint', 'Advanced nanotech exterior coating designed to withstand severe heat, heavy monsoon rain, and dampness in Rayalaseema.', 'Litre', 520, 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=800&auto=format&fit=crop', true),
('electricals-copper', 'Havells & Finolex Flame Retardant Copper Wires', 'Electricals', '100% electrolytic grade copper wires with FR-LSH (Flame Retardant Low Smoke Zero Halogen) insulation.', 'Coil', 1850, 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=800&auto=format&fit=crop', true),
('lighting-architectural', 'Modular COB Spotlights & Magnetic Track Lights', 'Lighting', 'Architectural glare-free anti-dazzle LED downlights and dimmable smart magnetic track lights.', 'Piece', 650, 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800&auto=format&fit=crop', true),
('security-cctv', 'Hikvision CP Plus 4K IP Camera & Smart Lock System', 'Security System', 'Smart home automation security kit including biometric door lock, video door phone, and remote CCTV mobile monitoring.', 'Set', 14500, 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?q=80&w=800&auto=format&fit=crop', true),
('hardware-door-lock', 'Yale & Hafele Digital Smart Door Locks', 'Hardware', 'Keyless biometric fingerprint and passcode door access hardware crafted with solid brass and SS 304.', 'Piece', 8500, 'https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=800&auto=format&fit=crop', true),
('fabrication-ss-glass', 'SS 304 Railings with Toughened Glass Panels', 'Fabrication', 'Laser-cut custom stainless steel railings with seamless frameless glass brackets for staircases and balcony edges.', 'Rft', 2400, 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=800&auto=format&fit=crop', true),
('plumbing-cpvc', 'Ashirvad & Astral CPVC Pro Pipes & Fittings', 'Plumbing', 'Lead-free hot & cold water CPVC piping system tested up to 93°C temperature resistance.', 'Length', 880, 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?q=80&w=800&auto=format&fit=crop', true),
('sanitary-kohler', 'Kohler & Jaquar Concealed Diverter & Wall-Hung Closet', 'Sanitary Ware', 'Luxury matte black and chrome thermostat shower columns with rimless soft-close wall-hung water closets.', 'Set', 18500, 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?q=80&w=800&auto=format&fit=crop', true),
('space-kitchen', 'German Engineered Island Modular Kitchen', 'Kitchen', 'Quartz stone breakfast counter, acrylic high-gloss shutters, tandem drawer units, and integrated Bosch appliances.', 'Set', 350000, 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?q=80&w=800&auto=format&fit=crop', true),
('space-bedroom', 'Custom Master Bedroom Wardrobe & Headboard Suite', 'Bedroom', 'Floor-to-ceiling tinted glass sliding wardrobes with sensor lighting, acoustic fabric headboard wall, and vanity dressers.', 'Set', 220000, 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?q=80&w=800&auto=format&fit=crop', true)
ON CONFLICT (id) DO NOTHING;
